### ISSUE TITLE
Imagenet error

### ISSUE THREAD

**Issue by Nancy0577** [TorchSSL/TorchSSL#12]
When we run the Imagenet, the error is 
ValueError: y should be a 1d array, got an array of shape (50000, 1000) instead.

**Comment by houwenxin** [comment]
Hi, could you paste the full error log here?

**Comment by Nancy0577** [comment]
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File
"/home/nancy/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py",
line 19, in _wrap
    fn(i, *args)
  File "/mnt/nvme1n1/TorchSSL-main/fixmatch.py", line 228, in main_worker
    trainer(args, logger=logger)
  File "/mnt/nvme1n1/TorchSSL-main/models/fixmatch/fixmatch.py", line 199,
in train
    eval_dict = self.evaluate(args=args)
  File
"/home/nancy/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py",
line 26, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/nvme1n1/TorchSSL-main/models/fixmatch/fixmatch.py", line 252,
in evaluate
    top5 = top_k_accuracy_score(y_true, y_logits, k=5)
  File
"/home/nancy/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_ranking.py",
line 1650, in top_k_accuracy_score
    y_score = column_or_1d(y_score) if y_type == 'binary' else y_score
  File
"/home/nancy/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py",
line 63, in inner_f
    return f(*args, **kwargs)
  File
"/home/nancy/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py",
line 864, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (50000, 1000)
instead.

HWX. ***@***.***> 于2021年11月19日周五 下午7:48写道：

**Comment by 18445864529** [comment]
I currently don't have time to reproduce this error but it seems that `top_k_accuracy` of sklearn is expecting `y` to be of shape (B, ) with each element ranging from 1\~C (1\~1000 or 0\~999), whereas your `y` is one-hot with shape (B, C). 

Maybe try upgrading your sklearn version so that there might be a chance it supports one-hot references (I don't know) or just simply make `y` of the shape it wants. Please try some workaround regarding this point and let us know if you still meet some problems.

Anyway, I'll have a check on it next week when I have time. If it's a bug we will fix it.
