### ISSUE TITLE
AMP training

### ISSUE THREAD

**Issue by anonymous4review-beep** [TorchSSL/TorchSSL#14]
Thanks for your great work! I've been looking for a torch-based SSL benchmark for a while and really appreciate your effort on this project!

Just a quick(and a bit stupid question):

While I was browsing the config files, I saw the option of amp training is always set to False. Is there a specific reason(such as performance degrade) for that? Or it's just a default setting that can be changed without losing anything?

Thanks again!

**Comment by 18445864529** [comment]
Theoretically, half-precision training does not lead to accuracy loss. But there do exist articles suggesting fp16 deteriorates the performance of EMA (https://arxiv.org/abs/2106.07759), thereby may have a chance to affect algorithms like MeanTeacher. So we disable it by default for safe, but we didn't test whether it affects accuracies, you can have a try :->

P.S. We are reproducing and about to update the benchmark results under the current repo version. If you were to compare the difference, please run both experiments by yourself instead of directly referring to the current benchmarks results.

**Comment by anonymous4review-beep** [comment]
Thanks for your reply!
