### ISSUE TITLE
CPL algorithm different implementation in code than in paper

### ISSUE THREAD

**Issue by Saurav-31** [TorchSSL/TorchSSL#33]
@qianlanwyd  Thanks for sharing the great repository. 

The algorithm in paper shows that the implementation should be like this 

``` python
pseudo_counter = Counter(selected_label.tolist()) # Compute estimated learning effect
if max(pseudo_counter.values()) < pseudo_counter[-1]:
```

whereas actual implemetation in the code seems to be a bit different 

``` python
pseudo_counter = Counter(selected_label.tolist())
if max(pseudo_counter.values()) < len(self.ulb_dset):  # not all(5w) -1
```

Also, `args.thresh_warmup` never changes in the code. Does that mean that we keep running the warmup for 2^20 iterations?

**Comment by 18445864529** [comment]
The `selected_label` is initialized as all -1's,
https://github.com/TorchSSL/TorchSSL/blob/4290520315e53d0569e0fd139e4f67ea847a949e/models/flexmatch/flexmatch.py#L123
the `pseudo_counter` thus will consist of almost -1's, whose number corresponds to the unused labels.
```
 if args.thresh_warmup:
      for i in range(args.num_classes):
          classwise_acc[i] = pseudo_counter[i] / max(pseudo_counter.values())
```
when thresh_warmup is used, the denominator can be simply set to the maximum value in the counter because this number will first be the number of -1's (used samples), and automatically change to the number of samples of the most dominant class, say class 4 for example, once there are more 4's than -1's. 
And if you disable thresh_warmup,
```
else:
    wo_negative_one = deepcopy(pseudo_counter)
    if -1 in wo_negative_one.keys():
        wo_negative_one.pop(-1)
```
the codes here will eliminate all -1's when choosing the denominator, meaning that the denominator will never consider unused samples but only the most dominant class.

`args.thresh_warmup` is used to control whether you employ thresh warmup or not.

As for this line, `if max(pseudo_counter.values()) < len(self.ulb_dset):` it's just to avoid the error that when disabling thresh warmup, for the first iteration, since there are 100% -1's, if you pop out all -1's, the denominator will be zero and thus ZeroDivisionError occurs, that's why we wait for at least one -1 turns to a valid number. 

Hope this makes sense to you :->

**Comment by Saurav-31** [comment]
@18445864529  Thanks for the detailed clarifications. It makes sense now to me, super helpful :)
