### ISSUE TITLE
tensorboard not working

### ISSUE THREAD

**Issue by nikoskaraliolios** [TorchSSL/TorchSSL#9]
Hello, and many thanks for creating this repo!

I've run several experiments, the log gives the expected results but when i run tensorboard I consistently get "No dashboards active". Am I doing something wrong?

**Comment by 18445864529** [comment]
Hi, thank you for your interest in this repo. 
May I ask how did you run the tensorboard, and do you have the `events.out.tfevents.<...>` file generated under `./saved_models/<exp_name>/tensorboard/`? 
If you have, you should be able to load tensorboard via `tensorboard --logdir <dir_of_eventsout>`. And if not, that's because currently the default writer of TBLog is 'custom', please either change the default value to 'tensorboard' or pass it from outside (e.g. fixmatch.py) to use the tensorboard writer, see: https://github.com/TorchSSL/TorchSSL/blob/9af6572f3e58f3b80cb003214ecbcb2537985223/train_utils.py#L139
https://github.com/TorchSSL/TorchSSL/blob/9af6572f3e58f3b80cb003214ecbcb2537985223/fixmatch.py#L97
I think this might be the reason. Maybe we need to add an argument control of the writer selection in the future.

**Comment by houwenxin** [comment]
Thanks for your feedback. We have updated the code and now it supports options to switch between tensorboard and local writer. Just run `git pull` and then append --use_tensorboard to your original command. Sorry for the inconvenience.

**Comment by nikoskaraliolios** [comment]
thanks, i'll check and let you know.

for the record, i had no events.out file in the tensorboard folder, only 3 .pkl files

**Comment by nikoskaraliolios** [comment]
i run the new version using the command `python flexmatch.py --c config/flexmatch/flexmatch_cifar10_40_1.yaml --use_tensorboard` and got the error

> File "/TorchSSL/flexmatch.py", line 229, in main_worker
    trainer(args, logger=logger)
> File "/TorchSSL/models/flexmatch/flexmatch.py", line 238, in train
    self.tb_log.update(tb_dict, self.it)
>  File "/TorchSSL/train_utils.py", line 156, in update
    if self.writer_type == "tensorboard":
>AttributeError: 'TBLog' object has no attribute 'writer_type'

**Comment by houwenxin** [comment]
Sorry, I have fixed the bug... Could you please pull again?

**Comment by nikoskaraliolios** [comment]
sorry if i'm abusing but now i got 2 event files in the folder but tensorboard still didn't see anything. the script ended with the same error and i keep getting 

>miniconda3/envs/ssl/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 31 leaked semaphores to clean up at shutdown
>  len(cache))

(thanks again)

**Comment by 18445864529** [comment]
I tested with the new argument, in your case, `python flexmatch.py --c config/flexmatch/flexmatch_cifar10_40_1.yaml --use_tensorboard`, and there was no error. 

The events.out file is the only thing needed for displaying tensorboard curves (running `tensorboard --logdir <dir_of_eventsout>` and then open the localhost in your browser.)

As for this new error you pasted, it just indicates the multiprocessing stopped unexpectedly and is not the real error message you should look at. The real traceback should be something above this message, so could you find it and paste it so that we can know what actually happened?

**Comment by nikoskaraliolios** [comment]
it actually worked this time, many thanks!
